swarm:
  agents: # supported: manager, analyst, googler, crunchbase_searcher
    - type: manager
      n: 2
    - type: analyst
      n: 2
    - type: googler
      n: 2
    - type: crunchbase_searcher # scraper can only have one job in parallel
      n: 1
  timeout_min: 10
  run_dir: ./tmp/swarm
task:
  role: |
    professional venture capital agency, who has a proven track reckord of consistently funding successful startups
  global_goal: |
    A new startup just send us their pitch. Find if the startup is worth investing in. The startup is called Brainamics and it is in the space of brain computer interfaces.
    More information about them: 'https://brainamics.de', 'https://www.linkedin.com/company/thebrainamics/'
  goals:
    - Generate a comprehensive description of the startup. Describe their value proposition, the product, USP and business model of a startup.
    - Find any mentions of the startup in the news, social media, etc. Add links.
    - Find top 10 companies and startups in this field. Find out their locations, raised funding, value proposition, differentiation, etc.
    - Find top 5 investors in this field. Includ specific details in the format of 'company AAA (link) invested in company BBB (link) $XX in year YYYY'
    - Describe the market size, growth rate and trends of this field.
    - Main problems and challenges of the field. Create an extensive list of problems. What can stop the field from growing? What can stop the company from succeeding?
    - Briefly describe the technology for the non-tech audience. Include links to the main articles in the field.
    - What questions should we ask the startup to make a more informed decision? Avoid generic and obvious questions and focus on field/domain specific questions that can uncover problems with this specific startup.
